<div class="mt-5 mb-5">
    <div class="row">
        <div class="col-sm-6">
            <img class="img-adver" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/banner2.png'); ?>" alt="Chưa có ảnh">
        </div>
        <div class="col-sm-6">
            <img class="img-adver" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/banner1.png'); ?>" alt="Chưa có ảnh">
        </div>
    </div>
</div>