<style>
    .title-deal{
        color: var(--primary-500, #93117B);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px; 
        letter-spacing: 0.7px;
    }
    .info-content{
        color: var(--body-default, #282828);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
</style>
<div class="mt-5">
<h1>Cirtus Juicer</h1>
        <hr class="mt-3">
        <div class="row">
            <div class="col-12">
                <div class="carousel-deal-of-day">
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                            <div class="content" style="width: 80%;">
                                <h4 class="title-deal">Multi cooker 9 Liters</h4>
                                <p class="info-content">$800</p>
                                <p class="info-content">$1000 </p>
                                <div class="star-icon">
                                    <p>*****</p>
                                </div>
                            </div>
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product2.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product3.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product4.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product5.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                 </div>
            </div>
        </div>
</div>

<div class="mt-5">
<h1>Blender </h1>
        <hr class="mt-3">
        <div class="row">
            <div class="col-12">
                <div class="carousel-deal-of-day">
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                            <div class="content" style="width: 80%;">
                                <h4 class="title-deal">Multi cooker 9 Liters</h4>
                                <p class="info-content">$800</p>
                                <p class="info-content">$1000 </p>
                                <div class="star-icon">
                                    <p>*****</p>
                                </div>
                            </div>
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product2.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product3.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product4.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product5.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                 </div>
            </div>
        </div>
</div>


<div class="mt-5">
<h1>Electric Oven </h1>
        <hr class="mt-3">
        <div class="row">
            <div class="col-12">
                <div class="carousel-deal-of-day">
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                            <div class="content" style="width: 80%;">
                                <h4 class="title-deal">Multi cooker 9 Liters</h4>
                                <p class="info-content">$800</p>
                                <p class="info-content">$1000 </p>
                                <div class="star-icon">
                                    <p>*****</p>
                                </div>
                            </div>
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product2.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product3.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product4.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product5.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                 </div>
            </div>
        </div>
</div>


<div class="mt-5">
<h1>Air Purifier</h1>
        <hr class="mt-3">
        <div class="row">
            <div class="col-12">
                <div class="carousel-deal-of-day">
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                            <div class="content" style="width: 80%;">
                                <h4 class="title-deal">Multi cooker 9 Liters</h4>
                                <p class="info-content">$800</p>
                                <p class="info-content">$1000 </p>
                                <div class="star-icon">
                                    <p>*****</p>
                                </div>
                            </div>
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product2.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product3.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product4.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product5.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                 </div>
            </div>
        </div>
</div>

<div class="mt-5">
<h1>Air-Conditioner </h1>
        <hr class="mt-3">
        <div class="row">
            <div class="col-12">
                <div class="carousel-deal-of-day">
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                            <div class="content" style="width: 80%;">
                                <h4 class="title-deal">Multi cooker 9 Liters</h4>
                                <p class="info-content">$800</p>
                                <p class="info-content">$1000 </p>
                                <div class="star-icon">
                                    <p>*****</p>
                                </div>
                            </div>
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product2.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product3.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product4.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product5.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                 </div>
            </div>
        </div>
</div>

<div class="mt-5">
<h1>Refrigerator</h1>
        <hr class="mt-3">
        <div class="row">
            <div class="col-12">
                <div class="carousel-deal-of-day">
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                            <div class="content" style="width: 80%;">
                                <h4 class="title-deal">Multi cooker 9 Liters</h4>
                                <p class="info-content">$800</p>
                                <p class="info-content">$1000 </p>
                                <div class="star-icon">
                                    <p>*****</p>
                                </div>
                            </div>
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product2.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product3.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product4.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product5.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product1.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                 </div>
            </div>
        </div>
</div>


