<div class="content-left">
    <div>
        <p class="price">790,000đ</p>
    </div>
    <div style="display:flex">
        <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/user.png'); ?>" alt="">
        <p>Member Prices</p>
    </div>
    <div class="cost">
        <p>648,000đ</p>
        <p>Price is discounted on the Shopping Cart/Checkout Page</p>
        <p>In Stock</p>
        <div class="menu-content">
            <ul>
                <li>Direct pouring head</li>
                <li>Stainless steel filter</li>
                <li>Wattage: 130W</li>
                <li>Anti-dripping</li>
                <li>Anti-slipping base</li>
            </ul>
            </hr>
        </div>
    </div>
</div> 