<style>
    .footerlink {
        color: var(--primary-000, #FAD2F2);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 500;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
    .menu li a {
        color: var(--primary-000, #FAD2F2);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 500;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
    .footertext a {
        color: var(--primary-000, #FAD2F2);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 500;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
</style>
<footer class="footer"><footer style="background-color: #DA6897;">
    <div class="container pt-5">
        <div class="row mb-5">
            <div class="col-3">
                <h4 class="headerfooter">QUICK LINKs</h4>
                <div class="mt-5">
                    <ul class="menu" style="list-style-type: none">
                        <li><a class="footerlink"  href="">Terms & Conditions</a></li>
                        <li><a class="footerlink" href="">Privacy Policies</a></li>
                        <li><a class="footerlink" href="">Delivery - Return - Warranty</a></li>
                        <li><a class="footerlink" href="">Payment Methods</a></li>
                        <li><a class="footerlink" href="">Loyalty Program</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-3">
                <h4 class="headerfooter">COMPANY</h4>
                <div class="mt-5">
                    <p class="footertext">
                        <a class="footerlink" href="">About us</a>
                    </p> 
                    <p class="footertext">
                        <a class="footerlink" href="">FAQs</a>
                    </p> 
                </div>
                <div class="mt-2">
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/nganhang.png'); ?>" alt="">
                </div>
            </div>
            <div class="col-3">
                <h4 class="headerfooter">Follow us</h4>
                <h4 class="headerfooter">Our Mobile Apps</h4>
                <div>
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/AppStore.png'); ?>" alt="">
                </div>
                <div>
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/googleplay.png'); ?>" alt="">
                </div>
            </div>
            <div class="col-3">
                <h4 class="headerfooter">CÔNG TY TNHH ĐIỆN TỬ SHARP VIỆT NAM</h4>
                <p class="footerlink">
                    Địa chỉ: T5-B03.07 & T5-B03.09, Lầu 3 Masteri Thảo Điền
                    159 Xa Lộ Hà Nội, Phường Thảo Điền, T.P Thủ Đức, T.P Hồ Chí Minh, Việt Nam
                </p>
                <p class="footerlink">
                    Email: <a href="/cdn-cgi/l/email-protection" class="__cf_email__" data-cfemail="5734243c3f173438343825383b3e3132792139">cskh@cocorolife.vn</a>
                </p>
                <p class="footerlink">
                    MST: 0308159258 Do Sở kế hoạch Đầu tư TP.HCM cấp ngày 13/3/2009
                </p>
                <p>
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/thongbao.png'); ?>" alt="">
                </p>
            </div>
        </div>
        <hr>
        <div class="row">
            <div class="col-6">
                <p class="footerlink">© 2023 Bản quyền của Minh Chiến</p>
            </div>
            <div class="col-6 text-end">
                <p>Our Payment Provider</p>
                <span style="display: inline-block;">
                    <p>
                        
                        <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/payyoo.png'); ?>" alt="">
                    </p>
                </span>
            </div>
        </div>
    </div>
</footer>