<div class="instruction">
        <div class="row">
            <div class="col-3">
                <div class="feature-content d-flex" style="margin-bottom: 25px;">
                    <div class="logo d-flex justify-content-center align-items-center m-0">
                        <img class="me-5" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/img1.png'); ?>" alt="Chưa có ảnh">
                    </div>
                    <div class="content d-flex justify-content-center flex-column">
                        <h4 class="title">Free Delivery</h4>
                        <p class="suptitle">For all orders over 1,000,000đ</p>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="feature-content d-flex">
                    <div class="logo d-flex justify-content-center align-items-center m-0">
                        <img class="me-5" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/img2.png'); ?>" alt="Chưa có ảnh">
                    </div>
                    <div class="content d-flex justify-content-center flex-column">
                        <h4 class="title">Authentic Products</h4>
                        <p class="suptitle">Legitiamte origin</p>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="feature-content d-flex">
                    <div class="logo d-flex justify-content-center align-items-center m-0">
                        <img class="me-5" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/img3.png'); ?>" alt="Chưa có ảnh">
                    </div>
                    <div class="content d-flex justify-content-center flex-column">
                        <h4 class="title">Secure Payment</h4>
                        <p class="suptitle">100% secure payment</p>
                    </div>
                </div>
            </div>
            <div class="col-3">
                <div class="feature-content d-flex">
                    <div class="logo d-flex justify-content-center align-items-center m-0">
                        <img class="me-5" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/img4.png'); ?>" alt="Chưa có ảnh">
                    </div>
                    <div class="content d-flex justify-content-center flex-column">
                        <h4 class="title">24/7 support</h4>
                        <p class="suptitle">Dedicated support</p>
                    </div>
                </div>
            </div>
        </div>
    </div>