<div style="background-color: #FAD2F2; max-width:1536px">
        <div class="row mt-5">
            <div class="row" style="padding-top: 50px;">
                <div class="col">
                    <h1>News</h1>
                    <hr>
                </div>
            </div>
            <div class="row">
                <div class="col-3">
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/new1.png') ?>" alt="">
                    <h3>How To Make A Fresh Juice Blended For Your Family?</h3>
                    <button>Organic</button>
                </div>
                <div class="col-3">
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/new2.png') ?>" alt="">
                    <h3>How To Make A Fresh Juice Blended For Your Family?</h3>
                    <button>Organic</button>
                </div>
                <div class="col-3">
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/new3.png') ?>" alt="">
                    <h3>How To Make A Fresh Juice Blended For Your Family?</h3>
                    <button>Organic</button>
                </div>
                <div class="col-3">
                    <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/new4.png') ?>" alt="">
                    <h3>How To Make A Fresh Juice Blended For Your Family?</h3>
                    <button style="background-color: #93117B; color: white;">Organic</button>
                </div>
            </div>
        </div>
     </div>