<style>
    .title-deal{
        color: var(--primary-500, #93117B);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px; 
        letter-spacing: 0.7px;
    }
    .info-content{
        color: var(--body-default, #282828);
        font-family: Quicksand;
        font-size: 14px;
        font-style: normal;
        font-weight: 700;
        line-height: 20px;
        letter-spacing: 0.7px;
    }
    .title_content{
        padding: 16px 0px;
        align-items: center;
        gap: 10px;
        background: var(--background-light, #F1F1F1);
        text-align: center;
    }
    .content_related{
        color: var(--body-default, #282828);
        text-align: center;
        font-family: Quicksand;
        font-size: 18px;
        font-style: normal;
        font-weight: 700;
        line-height: 24px; 
        letter-spacing: 0.9px;
    }
</style>
<div>
   <div class="title_content">
        <h1 class="content_related">Related Products</h1>
   </div>
        <hr class="mt-3">
        <div class="row">
            <div class="col-12">
                <div class="carousel-deal-of-day">
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product6.png'); ?>" alt=" Chưa có ảnh" />
                            <div class="content" style="width: 80%;">
                                <h4 class="title-deal">Sữa Dưỡng Phục Hồi Tái Tạo Da B5 Neogence 50ml</h4>
                                <div class="star-content" style="display: flex;">
                                    <div class="star-icon">
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                        <span class="fa fa-star checked"></span>
                                    </div>
                                    <p>185</p>     
                                </div>
                                <p class="info-content">Member Wednesday</p>
                                <p class="info-content">From 00:00 to 15:00 </p>
                                <p class="info-content">399,500 đ (-50%) </p>   
                            </div>
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product6.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product6.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product6.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product6.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product6.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                 </div>
            </div>
        </div>
</div>