<div class="mt-5">
<h1>Your Recently Viewed Products</h1>
        <hr class="mt-3">
        <div class="row">
            <div class="col-12">
                <div class="carousel-deal-of-day">
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product6.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product7.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product8.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product9.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product10.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                        <div class="product">
                            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/product6.png'); ?>" alt=" Chưa có ảnh" />
                        </div>
                 </div>
            </div>
        </div>
</div>
