<div class="container">
    <div class="row">
        <div class="col-8">
          <div id="carouselExampleInterval" class="carousel-slider" data-bs-ride="carousel">
            <div class="carousel-inner">
              <div class="carousel-item active" data-bs-interval="10000">
                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Slider.png'); ?>" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item" data-bs-interval="2000">
                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Slider.png'); ?>" class="d-block w-100" alt="...">
              </div>
              <div class="carousel-item">
                <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Slider.png'); ?>" class="d-block w-100" alt="...">
              </div>
            </div>
            <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Previous</span>
            </button>
            <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleInterval" data-bs-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="visually-hidden">Next</span>
            </button>
          </div>
        </div>

        <div class="col-4">
            <img class="mb-3" src="<?php echo $block->getViewFileUrl('Magento_Theme::images/Artboard.png'); ?>" alt="Chưa có ảnh" />
            <img src="<?php echo $block->getViewFileUrl('Magento_Theme::images/banner-facema_sk.png'); ?>" alt="Chưa có ảnh" />
        </div>
    </div>
</div>
